version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "100421"

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mondb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "100421"
