
###
POST http://localhost:8080/public/roles/ajouter
Content-Type: application/json

{
    "nom": "Depoivre",
    "motDePasse": "mdp",
    "role": "Medecin"
}

###
GET http://localhost:8080/public/roles/rechercher


###
PUT http://localhost:8080/public/roles/modifier/1
Content-Type: application/json

{
  "nom": "test",
  "motDePasse": "test",
  "role": "Medecin"
}


###
DELETE http://localhost:8080/private/roles/supprimer/1


